# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:48
from __future__ import unicode_literals

import apps.loginreg.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('first_name', models.CharField(max_length=45, validators=[apps.loginreg.models.validateName])),
                ('last_name', models.CharField(max_length=45, validators=[apps.loginreg.models.validateName])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, validators=[apps.loginreg.models.validatePasswordLength])),
                ('confirm_password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('auth_token', models.CharField(max_length=100)),
            ],
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
