# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0006_auto_20170212_2015'),
        ('loginreg', '0005_auto_20170212_2042'),
    ]

    operations = [
    ]
