# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 23:14
from __future__ import unicode_literals

import apps.reviews.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20170210_2314'),
        ('loginreg', '0003_auto_20170210_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('rating', models.PositiveIntegerField(validators=[apps.reviews.models.validateRating])),
                ('summary', models.TextField(max_length=10000)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginreg.User')),
            ],
        ),
    ]
